name: flutter_study_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

#闪屏页  终端输入命令flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: images/core_icon_bg_weather.png
  color: "#FFFFFF"
  android: true
  android_disable_fullscreen: true
  fill: true

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  english_words: ^3.1.0

  #强大的Dart Http请求库
  dio: ^4.0.0
  http: ^0.13.3

  # cookie
  dio_cookie_manager: ^2.0.0

  cookie_jar: ^3.0.1

  #scoped_model: ^1.0.1
  scoped_model: ^1.1.0

  #  #Flutter使用provide状态管理器管理界面
  #  provide: ^1.0.2

  #Flutter使用provider状态管理器管理界面   InheritedWidget的包装器 ，使它们更易于使用和更可重用
  provider: ^5.0.0

  #GetX 是 Flutter 上的一个轻量且强大的解决方案：高性能的状态管理、智能的依赖注入和便捷的路由管理  State Manager、Navigation Manager
  get: ^4.3.8

  #sharePreference
  get_storage: ^2.0.1

  #event_bus
  event_bus: ^2.0.0

  #shared_preferences: ^2.0.6
  shared_preferences: ^2.0.6

  #sqflite: ^2.0.0+3
  sqflite: ^2.0.0+3

  #toast
  #fluttertoast插件依赖原生
  fluttertoast: ^8.0.8

  #oktoast: ^3.1.1  包裹你的 MaterialApp,不是包裹你的 Scaffold
  oktoast: ^3.1.1

  flutter_easyloading: ^3.0.1

  flutter_screenutil: ^5.0.0+2

  #flutter 下拉刷新插件flutter_easyrefresh
  flutter_easyrefresh: ^2.2.1

  #下拉刷新和上拉加载的库
  pull_to_refresh: ^2.0.0

  #banner
  flutter_swiper: ^1.1.6

  #google_fonts
  google_fonts: ^2.1.0

  #闪屏页
  flutter_native_splash: ^1.2.1

  #date_format: ^2.0.4
  date_format: ^2.0.4

  #permission_handler ^8.1.6 权限访问
  permission_handler: ^8.1.6

  #image_picker: ^0.8.4 图片拾取器
  image_picker: ^0.8.4

  #webview_flutter: ^2.0.13 WebView插件
  webview_flutter: ^2.0.13

  #路径操作
  path: ^1.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  #  assets:
  #    - images/core_icon_bg_header.png
  #    - images/core_icon_bg_weather.png

  assets:
    - images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
